/*
Alpine.data('bliss', () => ({
  retail: {
    bronze: 0,
    awning: 0,
    pergola: 0,
    b6: 0,
    horiz_plank: 0,
    cedar_shake: 0,
    cedar_plank: 0,
    block: 0,
    plank: 0,
    lap: 0,
  },
  labels: {
    smallHomeOrientation: 'Left',
    bathFloorFinish: 'Ice Fog',
    cabinetFinish: 'White Shaker',
    counterFinish: 'Silverstone',
    doorColor: 'Factory Primed White',
    eavesColor: 'Unfinished Eaves',
    exteriorAddon: 'None',
    fasciaColor: 'Iron Gray',
    fixtureFinish: 'Matte Black',
    interiorKit: 'Bath/Small Kitchen (Right)',
    mainFloorFinish: 'Ashlar Oak',
    model: null,
    roofAddon: 'None',
    siding: 'Lap',
    sidingColor: 'Iron Gray',
    accentColor: 'Pearl Gray',
    soffitColor: 'Unfinished Roof Soffit',
    trimColor: 'Clear Anodized Aluminum',
    windowAddon: 'None',
    windowCasement: 'Pebble Gray',
    frontElevation: 'Default',
    backElevation: 'Default',
    leftElevation: 'Default',
    rightElevation: 'Default',
    smallHomeLayout: null,
    smallHomeKitchen: null,
    smallHomeExterior: null,
    aduHomePrimary: null,
    aduHomeSecondary: null,
    aduHomeBedroom: null,
    smallHomeRoof: null,
    summitNxCode: null,
  },
  config: {
    interiorPackage: 'lifestyle',
    interiorOrientation: 'R',
    smallHomeOrientation: 'L',
    useCase: null,
    elevationFrontFilter: 'default',
    elevationLeftFilter: 'default',
    elevationRightFilter: 'default',
    elevationBackFilter: 'default',
    backElevation: 'default',
    bathFloorFinish: 'ice-fog',
    cabinetFinish: 'white-shaker',
    counterFinish: 'silverstone',
    //depth: window.recipe.depth,
    doorColor: 'factory-primed-white',
    eavesColor: 'unfinished-eaves',
    exteriorAddon: 'none',
    fasciaColor: 'iron-gray',
    fixtureFinish: 'matte-black',
    frontElevation: 'default',
    interiorKit: 'shell-only',
    leftElevation: 'default',
    //length: window.recipe.length,
    mainFloorFinish: 'ashlar-oak',
    //model: window.recipe.model,
    model: null,
    rightElevation: 'default',
    roofAddon: 'none',
    siding: 'lap',
    sidingColor: 'iron-gray',
    size: null,
    soffitColor: 'unfinished-eaves',
    trimColor: 'aluminum',
    accentColor: 'pearl-gray',
    windowAddon: 'none',
    windowCasement: 'pebble-gray',
    smallHomeLayout: null,
    smallHomeKitchen: null,
    smallHomeExterior: null,
    smallHomeRoof: null,
    summitNxCode: null,
    aduHomePrimary: null,
    aduHomeSecondary: null,
    aduHomeBedroom: null,
  },
  customer: {
    first_name: '',
    last_name: '',
    email: '',
    phone: '',
    zip: '',
    // Use consistent naming with database columns
    is_store_associate: false,
    lowes_store_id: null,
    lowes_lead_generator: null,
  },
  rfc: {
    first_name: '',
    last_name: '',
    email: '',
    phone: '',
    zip: '',
    intended_use: '',
    for_existing_or_future_property: '',
    installation_preference: '',
    expected_timeline: '',
    possible_budget: '',
    message: ''
  },
  productCosts: {
    shell: 0,
    interiorKit: 0,
    kitchenLayout: 0,
    front: 0,
    back: 0,
    left: 0,
    right: 0,
    siding: 0,
    sidingColor: 0,
    eavesColor: 0,
    soffitColor: 0,
    trimColor: 0,
    doorColor: 0,
    windowAddon: 0,
    roofAddon: 0,
    exteriorAddon: 0,
    total: 0,
    totalWithDiscount: 0,
    roofStyle: 0,
    garageDoor: 0,
  },
  menuState: {
    loading: true,
    editMode: false,
    formMessage: '',
    colorMenu: 'siding',
    flooringMenu: 'main',
    finishesMenu: 'fixture',
    elevationsMenu: 'front',
    exteriorViewMenu: 'front',
    optionsMenu: 'exterior',
    sizeMenu: 'medium',
    showAllSizes: false,
    showDesignNav: false,
    showPriceMenuButton: false,
    showRFCButton: false,
    interiorOrientation: true,
    interiorFinishes: true,
    mainFloor: true,
    bathFloor: true,
    fixtureFinish: true,
    counterFinish: true,
    cabinetFinish: true,
    sidingColor: true,
    accentColor: false,
    soffitColor: true,
    trimColor: true,
    doorColor: true,
    eavesColor: false,
    fasciaColor: true,
    priceMenuOpen: false,
    floorPlanNavItem: true,
    sidingOptions: {},
    sizeNavItem: true,
    interiorNavItem: true,
    interiorFinishesNavItem: true,
    exteriorNavItem: true,
    exteriorFinishesNavItem: true,
    showPlankOption: true,
  },
  initializing: true,  
  showShellOnlyOverlay: false,
  menuOpen: false,
  show3DIcon: true,
  sprucePickerImageSrc: 'assets/images/spruce/spruce-picker-peppercorn.png',
  displayPrice: '$0.00',
  displayPriceWithDiscount: '$0.00',
  discountMessage: null,
  discountPercent: 0,
  discountInstall: null,
  activeSection: null,
  showAllSizesButton: 'Show all sizes',
  lowesOptions: [],
  selectedLowesSize: null,
  selectedLowesSeries: null,
  show360Modal: false,
  show3DIcon: true, 
  colorScheme: 'Clear',
  currentSlide: 0,
  maxSlides: 0,
  carouselRefs: [],
  showExploreLineupModal: false,
  enhanced360Viewer(model = 'summit-308', colorVariation = 'Clear') {
    return {
        images: [],
        loadedImages: {},
        currentImage: 0,
        dragging: false,
        lastX: 0,
        colorVariation,
        model,
        rotationInterval: null,
        rotationDelay: 100, // Time between rotations in ms
*/